version: '3.8'

services:

  # Node Service
  node_backend:
    image: node:18-alpine
    container_name: node_backend
    restart: unless-stopped
    working_dir: /usr/src/app
    env_file:
      - ./.env
    ports:
      - 3000:3000
    command: node .
    volumes:
      - ./:/usr/src/app

networks:
  default:
    name: docker_network



